### ISSUE TITLE
Rotate display not working on my display

### ISSUE THREAD

**Issue by ChuckRamsey** [kwindrem/RpiDisplaySetup#16]
**lcd_rotate=2** does not work on my display. However, **display_lcd_rotate=2** does!

No idea why ... but having both these in my config.txt does not seem to frustrate things so maybe you could add both these lines in RpiDisplaySetup?

**Comment by kwindrem** [comment]
Interesting. I noted that lcd_rotate affected the touch screen also but display_lcd_rotate did not. Since RpiDisplaySetup now includes touch screen calibration it's probably of less concern. 

I'll add display_lcd_rotate.

**Comment by ChuckRamsey** [comment]
👍

**Comment by seepv** [comment]
With a Pi3+ and the original 7“-Display - display_lcd_rotate=2 in /u-boot/config.txt doesn’t rotate the display, but lcd_rotate=2, as single entry, and a reboot, does rotate the display.
[ VenusOS v3.00~4 | RpiDisplaySetup v3.2 ]

**Comment by kwindrem** [comment]
Which is opposite what I found on RPI 4! Yikes. I may need to make this a choice when running the script.

**Comment by seepv** [comment]
That was a fast reply - RpiDisplaySetup v3.0 does also work OK with Pi3+ and Venus OS v3.00~4.

**Comment by kwindrem** [comment]
Are you saying I don't need to make changes? RpiDisplaySetup is currently at v3.2 and uses display_lcd_rotate.

Earlier versions used lcd_rotate but that was changed based on the input from ChuckRamsey above.

**Comment by seepv** [comment]
With RpiDisplaySetup v3.0 both of following entries, in /u-boot/config.txt does rotate the original 7“-Display after a reboot:
display_lcd_rotate=2
or
lcd_rotate=2
and both can stay active there (’not’ commented out) - but they have to be different like:

display_lcd_rotate=0
lcd_rotate=2
or
display_lcd_rotate=2
lcd_rotate=0

Two entries works also well with RpiDisplaySetup v3.2 and does rotate the display in both cases.
But as a single entry, and RpiDisplaySetup v3.2 - only lcd_rotate=2 works with a Pi3+.

[ System: Pi3+ | VenusOS v3.00~4 | RpiDisplaySetup v3.0 ]

**Comment by sledgehoe** [comment]
On my raspberry pi 2b+ with original 7" touch display
if you use display_lcd_rotate=2 it rotates the display but not the touch interface.
If i change it to lcd_rotate=2 everything works perfect as before.

It seeme there are some differences on other pi versions.

**Comment by ChuckRamsey** [comment]
This is very confusing. lcd_rotate=2 was removed (I think in 3.2) - so only display_lcd_rotate=2 - but now the display is rotated but touch is not. Adding it back makes it work properly. KAFKA!

I have a feeling my display is special ;) Might not be the official Rpi display. PI3B+, Venus's 3.00. I do remember having to spend oodles of time to get rotate to work - at the time on VenusOS 2.66

You may have to make it so that RpiDisplaySetup has an option "Rotating not working, try another way". 

I do remember having to spend oodles of time to get rotate to work

**Comment by seepv** [comment]
With an Pi3+ it’s the same behavior as with the Pi2+, Touch and Display are only synchronized with
lcd_rotate=2 in /u-boot/config.txt.

The entry display_lcd_rotate only flips the Display not the TouchFunktion in v3.0 and v3.2.
! Sorry - the previous check was only for visual not touch ! 

[ System: Pi3+ | VenusOS v3.00~4 | RpiDisplaySetup v3.0 and v3.2 ]

**Comment by kwindrem** [comment]
I have seen the same behavior with my RPI 4: lcd_rotate affects the touch also but display_lcd_rotate does not.

It this point, I'm suggesting that if you rotate the display you run the touch screen calibration which is not part of RpiDisplaySetup.

The next version of RpiDisplaySetup will also include an option to select which rotate command is installed in config.txt.

**Comment by kwindrem** [comment]
RpiDisplaySetup v3.3 is now available that includes a choice of which RPI display rotate command is installed
