### ISSUE TITLE
Display turns short on, off and on after awaking

### ISSUE THREAD

**Issue by AirTobe91** [kwindrem/RpiDisplaySetup#22]
Hello,

I sometimes have a strange behavior, when awaking my Waveshare 5" Amoled Display from blanking.
Sometimes when I touch the blanked screen, the screen turns on, 1 sec later off, 1sec later again on and then it stays on.
It's interesting, that it's not every time, I would say every second try...

Did you already experience such a problem? Could it be due to the display itself, or maybe something with the Raspberry?

Thank you!

**Comment by kwindrem** [comment]
I have no idea what could be causing this. It's either something in the display itself or in Venus Os. Nothing in RpiDisplaySetup could be causing it since that script just makes some connections then lets logic deep down in Venus OS manage the display.

**Comment by AirTobe91** [comment]
Ok, thank you! I consulted the display manufacturer and will see if there is maybe some additional configuration needed.
