### ISSUE TITLE
grey screen after VenusOS update to 3.00~32

### ISSUE THREAD

**Issue by teefixx** [kwindrem/RpiDisplaySetup#23]
Hi
Since updating from 3.00~14 to 3.00~32 I get only a grey, backlit screen. 

Uninstall and reinstall via Setup Helper did not help.

I use an RPi 3B and the [Official Raspberry Pi 7" Touchscreen Display.
Everything worked well before the update.

To reach and operate the interface via http is no problem.

Any suggestions what could be wrong?

thank you

**Comment by kwindrem** [comment]
I'm not seeing any problems here. You might look at the SetupHelper log file to see if there are any clues there.

**Comment by teefixx** [comment]
reinstalled setupHelper and RpiDisplaySetup, now it works. Thank you
