### ISSUE TITLE
Running Setup disables CAN Hat

### ISSUE THREAD

**Issue by badfrogg** [kwindrem/RpiDisplaySetup#24]
After running: /data/RpiDisplaySetup/setup , I loose the CAN Hat (VeCanSetup).

I have to reinstall it every time.

Here are my versions:
![image](https://github.com/kwindrem/RpiDisplaySetup/assets/17037082/3dd218e2-f9ed-49c4-9a3a-d30d2cebe8ff)
![image](https://github.com/kwindrem/RpiDisplaySetup/assets/17037082/1d86ab47-ef89-488b-9197-ed11493f0f2e)

**Comment by kwindrem** [comment]
Need more information:

Which CAN hat?

How are you installing it when it does work?

**Comment by badfrogg** [comment]
I am using the waveshare 2-ch isolated (Non-FD)

I am installing it through the GUI Package manager interface.

I should clarify, I am nopt loosing the installation of VeCanSetup. The can hat just stops working and reinstalling VeCanSetup brings it back.

**Comment by kwindrem** [comment]
You can not run VeCanSetup from PackageManager as it requires console interaction to configure the interfaces.

You must run /data/VeCanSetup/setup from a command line prompt either via ssh or a direct console connection.

Once you have added and configured ports via the command line., these settings will be restored when updating Venus OS (aka firmware update).

**Comment by badfrogg** [comment]
I did run VeCanSetup from the command line the first time I installed it. That worked fine. I was just reporting to you that running RpiDisplaySetup makes the CAN bus stop working.

It is not a problem for me becaus my screen is working now and I don't have a reason to run RpiDisplaySetup anymore. I just though you might like to know about the behavior. 

Thanks for contribution by the way!

**Comment by kwindrem** [comment]
fixed in v3.4

Thanks for the report, sorry for my misunderstanding.
