### ISSUE TITLE
Official 7" touchscreen - dims but doesn't blank

### ISSUE THREAD

**Issue by asderferjerkel** [kwindrem/RpiDisplaySetup#26]
Hey Kevin, appreciate all the work you put into these packages - they massively improve quality of life!

I've got an official 7" touchscreen running on a Pi 3B+ with RpiDisplaySetup 3.4. The brightness slider and screen timeout work as expected. However, when the screen timeout passes, the backlight turns off, but the display doesn't blank - I can still see the screen contents if I look closely. Just wondering if this is normal behaviour, or if there's something I've missed that's preventing blanking? Thanks!

**Comment by kwindrem** [comment]
I had to look very carefully with an intense light on the screen to see any image but it is there.
