### ISSUE TITLE
Raspberry Pi 7inch Display Rotation

### ISSUE THREAD

**Issue by FunkFamily** [kwindrem/RpiDisplaySetup#30]
Using the raspberry pi's 7 inch touchscreen with the lcd ribbon, the display works after installing "RpiDisplaySetup" but you have to edit config.txt in the u-boot directory with "lcd_rotate=2" to rotate in the proper orientation so that it works with all display housings.  I'll provide a picture of what it looks like after editing the config.txt file
![407050436_3717133245188235_542810770937370494_n](https://github.com/kwindrem/RpiDisplaySetup/assets/63885126/7aa07c6b-4c68-4335-a9d4-c4398932ac8d)

**Comment by kwindrem** [comment]
When you run RpiDisplaySetup's setup script, you are asked if you want to rotate the display. If so, the script adds that line to config.txt.

**Comment by FunkFamily** [comment]
I have never been asked after install. Is this something you have to initiate in a terminal

**Comment by kwindrem** [comment]
While you can auto-install RpiDisplaySetup from PackageManager, doing so uses defaults: the official RPI touchscreen with no rotation, default backlight and dimming.

if you need anything else, you need to run /data/RpiDisplaySetup/setup from the terminal or ssh. You are then prompted for your specific options.
