### ISSUE TITLE
Unable to rotate RPi 7" touch screen180 degrees

### ISSUE THREAD

**Issue by D0nJl0** [kwindrem/RpiDisplaySetup#31]
Installed GuiMods v8.29 after SetupHelper v5.17 and then installed RpiDisplaySetup v3.7.  Looking for how to rotate the 7" RPi touch screen.  Didn't see a toggle in any of the menu settings.  Is there a command line instructions to do this?  If so, can you point me there.  Thanks in advance.

**Comment by kwindrem** [comment]
Yes, you need to run /data/RpiDisplaySetup/setup script from the command line. Follow the prompts and you'll come across the choice to rotate the display or not. Refer to the ReadMe if needed.
