### ISSUE TITLE
RpiDisplaySetup V3.7 must be run from the command line

### ISSUE THREAD

**Issue by 58wolf** [kwindrem/RpiDisplaySetup#32]
Hi

I have  install Venus Large, Helper, Packagemanager and some packages on a Raspberry pi4. 

But RPiDIsplaySetup cannot be installed. Only from the command line.

I´m new in linux and need some info. 
I know to go via ssh to the rasp. 
where is the download package?
which command I need to install the package and if necessary with the Directory and filename and option for the command

Greets

**Comment by 58wolf** [comment]
I install the PI into a 10" Touch 

<img width="809" alt="Bildschirmfoto 2023-12-30 um 16 44 45" src="https://github.com/kwindrem/RpiDisplaySetup/assets/155248079/0d8d3c29-7e79-4853-bf49-93d44ac51d3f">

**Comment by kwindrem** [comment]
Looks like you got things installed.

If not the command to get to the setup script is

/data/RpiDisplaySetup/setup

Then follow the prompts

The ReadMe file in the package directory (/data/RpiDisplaySetup) or on GitHub will explain the choices more.

**Comment by 58wolf** [comment]
Thks

But which choice I use? 

Rasperry R , HDMI (H) or skip to config?

Resolution of the touchscreen is 1280x800

**Comment by kwindrem** [comment]
I can't answer your questions because I do not know what kind of display you are using. If you are plugging into an HDMI port on the PI, try that selection.

**Comment by 58wolf** [comment]
THks for help.
usd HDMI and than automaticly configure.

![Uploading IMG_5555.JPG…]()

**Comment by 58wolf** [comment]
![Uploading IMG_5556.JPG…]()
