### ISSUE TITLE
Helper files not found

### ISSUE THREAD

**Issue by sethpalenscar** [kwindrem/RpiDisplaySetup#34]
When attempting to run RpiDisplaySetup from the command line, I get a message that the helper files can't be found. Any suggestions on this issue?

**Comment by kwindrem** [comment]
Thanks for reporting. You found a bug. 
This occurs if running the setup script from inside /data/RpiDisplaySetup (or other package) directory (./setup). 

I'll fix this in a SetupHelper update I'm making now.

As a workaround, run the script as

/data/RpiDisplaySetup/setup
