### ISSUE TITLE
Screen rotation?

### ISSUE THREAD

**Issue by Shadow-Genesis** [kwindrem/RpiDisplaySetup#37]
I have a pi 2 b+ with the pi touch screen. My problem is more of how the case is made, but out of buying a new case its a simple one. My case has it installed upside down so I have to use the "lcd_rotate=2" in the config.txt to fix it.

So my question here is is there a more simple way to change it? Or can there be s setting added to the menu to control it?

I found updates will require me to re-add this every time.

**Comment by kwindrem** [comment]
There is an option to rotate the screen when running the setup script from the command line.

The script will prompt again for all options if you select install (i). If you have already run the script once and set all the options, you can choose reinstall (r) and all option prompts will be skipped, using the last set values.
