### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by MBj1703** [kwindrem/RpiDisplaySetup#38]
Hi,

I try to install the actual version on a RaspPi 3B with Venus OS large v3.34
The SetupHelper is installed and working, nothing else.
I got the following error: RiDisplaySetup install failed - setup must be run from the command line

<img width="488" alt="Bildschirmfoto 2024-07-11 um 11 33 43" src="https://github.com/kwindrem/RpiDisplaySetup/assets/15365164/a480f3e5-afd9-4a5d-b013-fcfbba698f29">

**Comment by kwindrem** [comment]
This is not really a failure. RpiDisplaySetup needs input from the installer (person) in order to make the correct configuration changes. You need ssh access to your Raspberry PI in order to perform the install.

**Comment by MBj1703** [comment]
??

Installation:

RpiDisplaySetup requires that SetupHelper is installed first.

The easiest way to install RpiDisplaySetup is to do a "blind install" of SetupHelper
	and then add the RpiDisplaySetup package via the PackageManager menus.

Refer to the SetupHelper ReadMe for instructions and for other install options:
	https://github.com/kwindrem/SetupHelper
